[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[unix_http_server]
file=/tmp/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[program:zookeeper]
command=zookeeper-server-start /etc/kafka/zookeeper.properties
autostart=true
autorestart=true
priority=1
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:kafka]
command=kafka-server-start /etc/kafka/server.properties
autostart=true
autorestart=true
priority=2
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:api]
command=/bin/sh -c "python3 -m uvicorn api.main:app --host 0.0.0.0 --port ${PORT:-8000}"
directory=/app
environment=KAFKA_BROKER="localhost:9092"
autostart=false
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:anomaly-detector]
command=python3 anomaly_detector.py
directory=/app
environment=KAFKA_BROKER="localhost:9092"
autostart=false
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:web-01]
command=python3 node_agent.py web-01
directory=/app
environment=KAFKA_BROKER="localhost:9092"
autostart=false
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:web-02]
command=python3 node_agent.py web-02
directory=/app
environment=KAFKA_BROKER="localhost:9092"
autostart=false
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:db-01]
command=python3 node_agent.py db-01
directory=/app
environment=KAFKA_BROKER="localhost:9092"
autostart=false
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:cache-01]
command=python3 node_agent.py cache-01
directory=/app
environment=KAFKA_BROKER="localhost:9092"
autostart=false
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:worker-01]
command=python3 node_agent.py worker-01
directory=/app
environment=KAFKA_BROKER="localhost:9092"
autostart=false
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
